# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CustoMood\Bundle\AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    CustoMoodAppBundle:User
                property: userName

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            provider: main
            logout:
                path:   user_logout
                target: user_login
                invalidate_session: true
            form_login:
                login_path: user_login
                check_path: user_login

    access_control:
        - { path: ^/user/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
